# Generated by Django 4.0.2 on 2022-07-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_author_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
