# Generated by Django 4.0.2 on 2022-07-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_article_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='quantity',
        ),
    ]
